FROM openjdk:13-jdk-alpine

# see https://github.com/docker-library/openjdk/issues/73
ENV LC_CTYPE en_US.UTF-8

RUN addgroup -S dtcgroup && adduser -S dtcuser -G dtcgroup

# configure system
RUN echo "add needed tools" && \
    apk update && \
    apk add --no-cache bash vim git graphviz fontconfig fontconfig-dev msttcorefonts-installer ttf-dejavu

SHELL ["/bin/bash", "-c"]

USER dtcuser
WORKDIR /home/dtcuser
ENV HOME=/home/dtcuser

ENV GRADLE_USER_HOME=/home/dtcuser/.gradle

RUN git clone --branch ng https://github.com/docToolchain/docToolchain.git && \
    cd docToolchain && \
    # checkout specific version
    git fetch --tags && \
    git checkout v2.0.2 && \
    git submodule update -i && \
    # remove .git folders
    rm -rf `find -type d -name .git` && \
    umask g+w && \
    ./gradlew tasks && \
    ./gradlew dependencies && \
    chmod -R o=u $GRADLE_USER_HOME && \
    chmod -R g=u $GRADLE_USER_HOME && \
    rm -r $GRADLE_USER_HOME/daemon && \
    chmod -R o=u $HOME

ENV PATH "/home/dtcuser/docToolchain/bin:$PATH"

RUN echo $PATH

USER dtcuser

WORKDIR /project

VOLUME /project

ENTRYPOINT /bin/bash


